// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCruDmAwtUoqOEc1WxJTQnV2a8wrhfQ41U',
    appId: '1:929028972165:android:e20be3c0096d91d84653ec',
    messagingSenderId: '929028972165',
    projectId: 'nursecallalram',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCruDmAwtUoqOEc1WxJTQnV2a8wrhfQ41U',
    appId: '1:929028972165:android:e20be3c0096d91d84653ec',
    messagingSenderId: '929028972165',
    projectId: 'nursecallalram',
    iosBundleId: 'com.example.nursecallalram',
  );
}
